// SPDX-License-Identifier: Apache-2.0

package logpipe

import (
	"regexp"
	"slices"
	"sort"
	"strings"
	"time"
)

// consolidator_gostack.go — the Go goroutine-dump consolidator.
//
// A Go runtime crash arrives as dozens of one-line templates. This pass groups
// the fragments by temporal proximity and merges each group of three or more
// into one CRITICAL template. BELOW THREE FRAGMENTS THE INPUT PASSES THROUGH
// UNTOUCHED, and a group of one or two inside a larger fragment set does too:
// two stack lines are not a crash.

type goStackConsolidator struct{}

// Consolidate merges Go stack fragments and reports what each merged template
// absorbed.
func (g *goStackConsolidator) Consolidate(templates []*Template) Consolidation {
	var fragments, normal []*Template
	for _, t := range templates {
		if isGoStackFragment(t) {
			fragments = append(fragments, t)
		} else {
			normal = append(normal, t)
		}
	}
	// BELOW THREE FRAGMENTS THE INPUT IS RETURNED AS IT ARRIVED, order included.
	// The per-group check further down would also merge nothing here, so what
	// this early return actually decides is that a set too small to be a crash
	// is not RESHUFFLED into fragments-last order for nothing. The test asserts
	// the order, because the count alone cannot tell this branch from its
	// absence.
	if len(fragments) < 3 {
		return Consolidation{Templates: templates}
	}

	sort.Slice(fragments, func(i, j int) bool { return fragments[i].LastSeen.Before(fragments[j].LastSeen) })

	absorbed := make(map[string][]string)
	for _, group := range groupByTime(fragments, 30*time.Second) {
		if len(group) < 3 {
			normal = append(normal, group...)
			continue
		}
		merged := mergeGoStackGroup(group)
		normal = append(normal, merged)
		for _, t := range group {
			absorbed[merged.ID] = append(absorbed[merged.ID], t.ID)
		}
	}
	if len(absorbed) == 0 {
		return Consolidation{Templates: normal}
	}
	return Consolidation{Templates: normal, Absorbed: absorbed}
}

// mergeGoStackGroup folds one temporal group into a single CRITICAL template.
//
// THE MERGED TEMPLATE CARRIES A REAL ID, derived from its own pattern by the
// same rule every other template's id comes from. The built-in pipeline leaves
// it empty, which is what puts a node with an empty id in the batch and makes
// the absorber unusable as a remap target.
func mergeGoStackGroup(group []*Template) *Template {
	merged := &Template{
		Pattern:   "Go runtime crash (goroutine dump)",
		Severity:  SeverityCritical,
		FirstSeen: group[0].FirstSeen,
		LastSeen:  group[0].LastSeen,
	}
	for _, t := range group {
		merged.Count += t.Count
		if t.FirstSeen.Before(merged.FirstSeen) {
			merged.FirstSeen = t.FirstSeen
		}
		if t.LastSeen.After(merged.LastSeen) {
			merged.LastSeen = t.LastSeen
		}
		if SeverityIndex(t.Severity) > SeverityIndex(merged.Severity) {
			merged.Severity = t.Severity
		}
		if len(merged.ExampleVars) < 3 &&
			(reGoStack.MatchString(t.Pattern) || reExceptionHeader.MatchString(t.Pattern)) {
			ex := t.Pattern
			if len(t.ExampleVars) > 0 {
				ex = strings.Join(t.ExampleVars[0], " ")
			}
			merged.ExampleVars = append(merged.ExampleVars, []string{ex})
		}
	}
	if len(merged.ExampleVars) == 0 {
		if len(group[0].ExampleVars) > 0 {
			merged.ExampleVars = [][]string{group[0].ExampleVars[0]}
		} else {
			merged.ExampleVars = [][]string{{group[0].Pattern}}
		}
	}
	merged.ID = TemplateID(merged.Pattern)
	merged.Alias = TemplateAliasFor(merged)
	return merged
}

// groupByTime splits a LastSeen-sorted slice wherever the gap between one
// template's end and the next one's start exceeds the window.
func groupByTime(sorted []*Template, window time.Duration) [][]*Template {
	if len(sorted) == 0 {
		return nil
	}
	var groups [][]*Template
	current := []*Template{sorted[0]}
	for i := 1; i < len(sorted); i++ {
		if sorted[i].FirstSeen.Sub(current[len(current)-1].LastSeen) <= window {
			current = append(current, sorted[i])
			continue
		}
		groups = append(groups, current)
		current = []*Template{sorted[i]}
	}
	return append(groups, current)
}

// The Go stack-frame detection patterns.
var (
	reGoFuncCall     = regexp.MustCompile(`^[\w.*/()\-:]+\.\w+\(`)
	reGoStackArgs    = regexp.MustCompile(`\((0x[0-9a-fA-F]|\.\.\.|\{\}|\)|\{0x|[0-9a-fA-F]+\?|0x)`)
	reGoSourceRef    = regexp.MustCompile(`\.go:\d+`)
	reGoSSourceRef   = regexp.MustCompile(`\.s:\d+`)
	reGoPCOffset     = regexp.MustCompile(`\+0x[0-9a-fA-F]+`)
	reGoRegisterDump = regexp.MustCompile(
		`^(rax|rbx|rcx|rdx|rsi|rdi|rbp|rsp|r[89]|r1[0-5]|eax|ebx|ecx|edx|` +
			`gs|fs|cs|rflags|eflags|rip|eip)\s+0x`)
	reGoCreatedBy     = regexp.MustCompile(`^created by\s+`)
	reGoSignalInfo    = regexp.MustCompile(`^(PC=0x|SIG[A-Z]+[: ]|signal )`)
	reGoAutogenerated = regexp.MustCompile(`^<autogenerated>:\d+`)
)

func isGoStackFragment(t *Template) bool {
	return matchesGoStackPattern(t.Pattern) || exampleVarsContain(t.ExampleVars, matchesGoStackPattern)
}

// exampleVarsContain reports whether any example row, joined, satisfies fn.
func exampleVarsContain(vars [][]string, fn func(string) bool) bool {
	return slices.ContainsFunc(vars, func(row []string) bool { return fn(strings.Join(row, " ")) })
}

func normalizeStackLine(msg string) string {
	msg = strings.TrimLeft(msg, " \t")
	msg = strings.TrimPrefix(msg, ">")
	return strings.TrimLeft(msg, " \t")
}

// matchesGoStackPattern is deliberately negative-first: a JSON object, an array,
// a timestamped line and a logfmt line are rejected before any positive test
// runs, because a false positive here folds unrelated templates into a crash.
func matchesGoStackPattern(msg string) bool {
	norm := normalizeStackLine(msg)
	if len(norm) == 0 {
		return false
	}
	if norm[0] == '{' || norm[0] == '[' {
		return false
	}
	if len(norm) > 4 && norm[0] >= '0' && norm[0] <= '9' && norm[4] == '-' {
		return false
	}
	if strings.HasPrefix(norm, "time=") || strings.HasPrefix(norm, "ts=") {
		return false
	}
	if len(norm) > 300 && !reGoSourceRef.MatchString(norm) && !reGoPCOffset.MatchString(norm) {
		return false
	}
	return matchesHighConfidence(norm) || matchesSourceRef(norm) || matchesFuncCall(norm)
}

// matchesHighConfidence covers the shapes nothing but a Go runtime emits.
func matchesHighConfidence(norm string) bool {
	return reGoStack.MatchString(norm) ||
		reGoRegisterDump.MatchString(norm) ||
		reGoCreatedBy.MatchString(norm) ||
		reGoSignalInfo.MatchString(norm) ||
		reGoAutogenerated.MatchString(norm)
}

// matchesSourceRef accepts a .go:NNN or .s:NNN reference only when it also
// carries a program-counter offset or an absolute path, so an ordinary log line
// naming a source file is not a stack frame.
func matchesSourceRef(norm string) bool {
	return sourceRefLooksLikeFrame(reGoSourceRef, norm) || sourceRefLooksLikeFrame(reGoSSourceRef, norm)
}

func sourceRefLooksLikeFrame(re *regexp.Regexp, norm string) bool {
	if !re.MatchString(norm) || len(norm) >= 200 {
		return false
	}
	if reGoPCOffset.MatchString(norm) {
		return true
	}
	trimmed := strings.TrimLeft(norm, " \t")
	return len(trimmed) > 0 && trimmed[0] == '/'
}

func matchesFuncCall(norm string) bool {
	return reGoFuncCall.MatchString(norm) && len(norm) < 300 && reGoStackArgs.MatchString(norm)
}
