// SPDX-License-Identifier: Apache-2.0

package logpipe

import (
	"regexp"
	"strings"
	"time"
)

// consolidator_gostack.go — Go runtime crash dumps.
//
// A goroutine dump is one event and dozens of lines. Recognizing it takes more
// than one regex because the lines are not alike: the header, the register
// dump, the `created by` line, the source references and the function calls are
// five different shapes, and prose that merely mentions a `.go:` file is none
// of them. The rejections below carry as much weight as the matches.

type goStackConsolidator struct{}

func (g *goStackConsolidator) Name() string { return "go_stack" }

// goStackWindow bounds how far apart two fragments may be and still belong to
// one dump. A goroutine dump is written in a burst, so thirty seconds is
// generous; it is wide rather than tight because a slow writer splitting one
// dump into two templates is the worse failure.
const goStackWindow = 30 * time.Second

// Consolidate merges temporal groups of three or more Go stack fragments into
// one CRITICAL template each.
func (g *goStackConsolidator) Consolidate(templates []*Template) []*Template {
	var fragments, normal []*Template
	for _, t := range templates {
		if isGoStackFragment(t) {
			fragments = append(fragments, t)
		} else {
			normal = append(normal, t)
		}
	}
	if len(fragments) < minFragmentsToMerge {
		return templates
	}
	sortByLastSeen(fragments)
	for _, group := range groupByTime(fragments, goStackWindow) {
		if len(group) < minFragmentsToMerge {
			normal = append(normal, group...)
			continue
		}
		normal = append(normal, mergeGoStackGroup(group))
	}
	return normal
}

// mergeGoStackGroup folds a group into one template. The merged template's
// alias is derived HERE rather than left to the caller, because the merged
// pattern and severity are both new.
func mergeGoStackGroup(group []*Template) *Template {
	merged := &Template{
		Pattern:   "Go runtime crash (goroutine dump)",
		Severity:  SeverityCritical,
		FirstSeen: group[0].FirstSeen,
		LastSeen:  group[0].LastSeen,
	}
	for _, t := range group {
		merged.Count += t.Count
		if t.FirstSeen.Before(merged.FirstSeen) {
			merged.FirstSeen = t.FirstSeen
		}
		if t.LastSeen.After(merged.LastSeen) {
			merged.LastSeen = t.LastSeen
		}
		if SeverityIndex(t.Severity) > SeverityIndex(merged.Severity) {
			merged.Severity = t.Severity
		}
		if len(merged.ExampleVars) >= maxExampleVars {
			continue
		}
		if !reGoStack.MatchString(t.Pattern) && !reExceptionHeader.MatchString(t.Pattern) {
			continue
		}
		ex := t.Pattern
		if len(t.ExampleVars) > 0 {
			ex = strings.Join(t.ExampleVars[0], " ")
		}
		merged.ExampleVars = append(merged.ExampleVars, []string{ex})
	}
	if len(merged.ExampleVars) == 0 {
		// Nothing in the group looked like a header, so keep the first
		// fragment as the example: a merged crash with no example at all is
		// unreadable to whoever has to diagnose it.
		if len(group[0].ExampleVars) > 0 {
			merged.ExampleVars = [][]string{group[0].ExampleVars[0]}
		} else {
			merged.ExampleVars = [][]string{{group[0].Pattern}}
		}
	}
	merged.ID = TemplateID(merged.Pattern)
	merged.Alias = TemplateAliasFor(merged)
	return merged
}

// The Go stack shapes.
var (
	reGoFuncCall     = regexp.MustCompile(`^[\w.*/()\-:]+\.\w+\(`)
	reGoStackArgs    = regexp.MustCompile(`\((0x[0-9a-fA-F]|\.\.\.|\{\}|\)|\{0x|[0-9a-fA-F]+\?|0x)`)
	reGoSourceRef    = regexp.MustCompile(`\.go:\d+`)
	reGoSSourceRef   = regexp.MustCompile(`\.s:\d+`)
	reGoPCOffset     = regexp.MustCompile(`\+0x[0-9a-fA-F]+`)
	reGoRegisterDump = regexp.MustCompile(
		`^(rax|rbx|rcx|rdx|rsi|rdi|rbp|rsp|r[89]|r1[0-5]|eax|ebx|ecx|edx|` +
			`gs|fs|cs|rflags|eflags|rip|eip)\s+0x`)
	reGoCreatedBy     = regexp.MustCompile(`^created by\s+`)
	reGoSignalInfo    = regexp.MustCompile(`^(PC=0x|SIG[A-Z]+[: ]|signal )`)
	reGoAutogenerated = regexp.MustCompile(`^<autogenerated>:\d+`)
)

// goStackProseLimit and goStackLineLimit bound how long a line may be and still
// be read as a stack frame. A stack frame is short; a long line mentioning a Go
// source file is prose that quoted one.
const (
	goStackProseLimit = 300
	goStackLineLimit  = 200
)

func isGoStackFragment(t *Template) bool {
	return matchesGoStackPattern(t.Pattern) || exampleVarsContain(t.ExampleVars, matchesGoStackPattern)
}

// normalizeStackLine strips the indentation and quote markers a log pipeline
// adds, so a frame nested inside a JSON message still matches.
func normalizeStackLine(msg string) string {
	msg = strings.TrimLeft(msg, " \t")
	msg = strings.TrimPrefix(msg, ">")
	return strings.TrimLeft(msg, " \t")
}

// matchesGoStackPattern reports whether a line is part of a goroutine dump.
// The four rejections come first and each has a reason: a JSON object or array
// is structured output, a leading date is a timestamped log line, a logfmt
// prefix is the same, and long prose without a Go marker is prose.
func matchesGoStackPattern(msg string) bool {
	norm := normalizeStackLine(msg)
	if norm == "" {
		return false
	}
	if norm[0] == '{' || norm[0] == '[' {
		return false
	}
	if len(norm) > 4 && norm[0] >= '0' && norm[0] <= '9' && norm[4] == '-' {
		return false
	}
	if strings.HasPrefix(norm, "time=") || strings.HasPrefix(norm, "ts=") {
		return false
	}
	if len(norm) > goStackProseLimit && !reGoSourceRef.MatchString(norm) && !reGoPCOffset.MatchString(norm) {
		return false
	}
	return matchesHighConfidence(norm) || matchesSourceRef(norm) || matchesFuncCall(norm)
}

// matchesHighConfidence covers the shapes nothing else produces.
func matchesHighConfidence(norm string) bool {
	return reGoStack.MatchString(norm) ||
		reGoRegisterDump.MatchString(norm) ||
		reGoCreatedBy.MatchString(norm) ||
		reGoSignalInfo.MatchString(norm) ||
		reGoAutogenerated.MatchString(norm)
}

// matchesSourceRef covers a `.go:NNN` or `.s:NNN` reference that also carries a
// program-counter offset or an absolute path — the two things that separate a
// stack frame from a log line naming a file.
func matchesSourceRef(norm string) bool {
	return sourceRefFrame(norm, reGoSourceRef) || sourceRefFrame(norm, reGoSSourceRef)
}

func sourceRefFrame(norm string, ref *regexp.Regexp) bool {
	if !ref.MatchString(norm) || len(norm) >= goStackLineLimit {
		return false
	}
	if reGoPCOffset.MatchString(norm) {
		return true
	}
	trimmed := strings.TrimLeft(norm, " \t")
	return trimmed != "" && trimmed[0] == '/'
}

// matchesFuncCall covers a function call whose arguments look like a frame's:
// hex pointers, elided values or an empty struct.
func matchesFuncCall(norm string) bool {
	return reGoFuncCall.MatchString(norm) && len(norm) < goStackProseLimit && reGoStackArgs.MatchString(norm)
}
