// SPDX-License-Identifier: Apache-2.0

package main

import (
	"regexp"
	"slices"
	"sort"
	"strings"
	"time"
)

// consolidate_gostack.go — recognizing Go goroutine-dump fragments and merging
// each temporal group of three or more into one CRITICAL template.
//
// THE GROUP-SIZE FLOOR IS BEHAVIOR: a group of two passes through untouched.
// Two stack-shaped lines are as likely to be ordinary log output as a crash,
// and merging them would erase two real templates.

// goStackWindow is how far apart two fragments may be and still belong to one
// dump.
const goStackWindow = 30 * time.Second

// goStackMinGroup is the smallest group that merges.
const goStackMinGroup = 3

// goStackMergedPattern is the merged survivor's pattern. It is a fixed
// sentence, not a sample line: the fragments it replaces are dozens of distinct
// frames and none of them describes the event.
const goStackMergedPattern = "Go runtime crash (goroutine dump)"

type goStackConsolidator struct{}

func (g *goStackConsolidator) Name() string { return "go_stack" }

// Consolidate partitions the templates, groups the fragments by temporal
// proximity and merges each group of three or more.
func (g *goStackConsolidator) Consolidate(templates []*LogTemplate) ConsolidationResult {
	var fragments, normal []*LogTemplate
	for _, t := range templates {
		if isGoStackFragment(t) {
			fragments = append(fragments, t)
		} else {
			normal = append(normal, t)
		}
	}
	if len(fragments) < goStackMinGroup {
		return ConsolidationResult{Templates: templates}
	}

	sort.SliceStable(fragments, func(i, j int) bool {
		return fragments[i].LastSeen.Before(fragments[j].LastSeen)
	})

	var absorptions []Absorption
	for _, group := range groupByTime(fragments, goStackWindow) {
		if len(group) < goStackMinGroup {
			normal = append(normal, group...)
			continue
		}
		merged := mergeGoStackGroup(group)
		normal = append(normal, merged)
		absorptions = append(absorptions, Absorption{Survivor: merged, Fragments: fragmentIDs(group)})
	}
	survivors, absorptions := dedupeMergedSurvivors(normal, absorptions)
	return ConsolidationResult{Templates: survivors, Absorptions: absorptions}
}

// mergeGoStackGroup folds a group into one CRITICAL template, keeping a few
// example lines so a reader can see what crashed.
func mergeGoStackGroup(group []*LogTemplate) *LogTemplate {
	merged := &LogTemplate{
		Pattern:   goStackMergedPattern,
		Severity:  SeverityCritical,
		FirstSeen: group[0].FirstSeen,
		LastSeen:  group[0].LastSeen,
	}
	for _, t := range group {
		absorbInto(merged, t)
		collectGoStackExample(merged, t)
	}
	if len(merged.ExampleVars) == 0 {
		merged.ExampleVars = [][]string{fallbackExample(group[0])}
	}
	return finishMerged(merged)
}

// collectGoStackExample keeps up to maxExampleVars header-ish lines from the
// group, preferring a fragment's captured variables over its wildcarded
// pattern, since the pattern of a stack line is mostly wildcards.
func collectGoStackExample(merged, t *LogTemplate) {
	if len(merged.ExampleVars) >= maxExampleVars {
		return
	}
	if !reGoStack.MatchString(t.Pattern) && !reExceptionHeader.MatchString(t.Pattern) {
		return
	}
	example := t.Pattern
	if len(t.ExampleVars) > 0 {
		example = strings.Join(t.ExampleVars[0], " ")
	}
	merged.ExampleVars = append(merged.ExampleVars, []string{example})
}

// fallbackExample is the example a merged template carries when no fragment
// looked like a header.
func fallbackExample(t *LogTemplate) []string {
	if len(t.ExampleVars) > 0 {
		return t.ExampleVars[0]
	}
	return []string{t.Pattern}
}

// The detection patterns. reGoStack and reExceptionHeader are shared with the
// Python consolidator's header selection.
var (
	reGoStack         = regexp.MustCompile(`^goroutine\s+\d+`)
	reExceptionHeader = regexp.MustCompile(`(?i)^(exception|error|panic|traceback|caused by|fatal)`)

	reGoFuncCall     = regexp.MustCompile(`^[\w.*/()\-:]+\.\w+\(`)
	reGoStackArgs    = regexp.MustCompile(`\((0x[0-9a-fA-F]|\.\.\.|\{\}|\)|\{0x|[0-9a-fA-F]+\?|0x)`)
	reGoSourceRef    = regexp.MustCompile(`\.go:\d+`)
	reGoSSourceRef   = regexp.MustCompile(`\.s:\d+`)
	reGoPCOffset     = regexp.MustCompile(`\+0x[0-9a-fA-F]+`)
	reGoRegisterDump = regexp.MustCompile(
		`^(rax|rbx|rcx|rdx|rsi|rdi|rbp|rsp|r[89]|r1[0-5]|eax|ebx|ecx|edx|` +
			`gs|fs|cs|rflags|eflags|rip|eip)\s+0x`)
	reGoCreatedBy     = regexp.MustCompile(`^created by\s+`)
	reGoSignalInfo    = regexp.MustCompile(`^(PC=0x|SIG[A-Z]+[: ]|signal )`)
	reGoAutogenerated = regexp.MustCompile(`^<autogenerated>:\d+`)
)

// isGoStackFragment tests a template's pattern AND its captured examples,
// because a stack frame whose variable parts were masked has a pattern of
// mostly wildcards while its examples still carry the frame text.
func isGoStackFragment(t *LogTemplate) bool {
	return matchesGoStackPattern(t.Pattern) || exampleVarsContain(t.ExampleVars, matchesGoStackPattern)
}

// exampleVarsContain reports whether any example row, joined, satisfies fn.
func exampleVarsContain(vars [][]string, fn func(string) bool) bool {
	return slices.ContainsFunc(vars, func(row []string) bool { return fn(strings.Join(row, " ")) })
}

// normalizeStackLine strips the leading indentation and quote marker a log
// wrapper adds, so an indented frame is recognized.
func normalizeStackLine(msg string) string {
	msg = strings.TrimLeft(msg, " \t")
	msg = strings.TrimPrefix(msg, ">")
	return strings.TrimLeft(msg, " \t")
}

// matchesGoStackPattern reports whether a line looks like a Go stack frame.
//
// The four negative guards come first and each excludes a shape that would
// otherwise match: a JSON object or array, a timestamped log line, a
// logfmt-style line, and long prose carrying no Go marker at all.
func matchesGoStackPattern(msg string) bool {
	norm := normalizeStackLine(msg)
	if len(norm) == 0 {
		return false
	}
	if norm[0] == '{' || norm[0] == '[' {
		return false
	}
	if len(norm) > 4 && norm[0] >= '0' && norm[0] <= '9' && norm[4] == '-' {
		return false
	}
	if strings.HasPrefix(norm, "time=") || strings.HasPrefix(norm, "ts=") {
		return false
	}
	if len(norm) > 300 && !reGoSourceRef.MatchString(norm) && !reGoPCOffset.MatchString(norm) {
		return false
	}
	return matchesHighConfidence(norm) || matchesSourceRef(norm) || matchesFuncCall(norm)
}

// matchesHighConfidence covers the shapes that are unambiguously Go runtime
// output.
func matchesHighConfidence(norm string) bool {
	return reGoStack.MatchString(norm) ||
		reGoRegisterDump.MatchString(norm) ||
		reGoCreatedBy.MatchString(norm) ||
		reGoSignalInfo.MatchString(norm) ||
		reGoAutogenerated.MatchString(norm)
}

// matchesSourceRef covers a source-file reference that also looks like a frame:
// it must carry a program-counter offset or start at an absolute path, or an
// ordinary application log line naming a .go file would match.
func matchesSourceRef(norm string) bool {
	if len(norm) >= 200 {
		return false
	}
	if !reGoSourceRef.MatchString(norm) && !reGoSSourceRef.MatchString(norm) {
		return false
	}
	if reGoPCOffset.MatchString(norm) {
		return true
	}
	trimmed := strings.TrimLeft(norm, " \t")
	return len(trimmed) > 0 && trimmed[0] == '/'
}

// matchesFuncCall covers a call with stack-shaped arguments — hex addresses,
// ellipses, empty structs.
func matchesFuncCall(norm string) bool {
	return reGoFuncCall.MatchString(norm) && len(norm) < 300 && reGoStackArgs.MatchString(norm)
}
